### ISSUE TITLE
The uploader icon & text

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/quick-brown-fox#10]
The icon here is still the old shield and I think we should tweak the text a bit to say.

"Drop fonts here or click to upload."

<img width="342" alt="screen shot 2019-01-18 at 10 46 08 am" src="https://user-images.githubusercontent.com/158918/51400570-5f11b980-1b0e-11e9-88ab-a31dcbf4812c.png">

**Comment by jrtashjian** [comment]
Good catch!

**Comment by jrtashjian** [comment]
Fixed in 2098815087e6b62c8e47c2aea63950b5216e4dce
