### ISSUE TITLE
Customize Options

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/quick-brown-fox#4]
Could we give the people the option to customize the sentence, paragraph, etc?

People will probably ask for this ability and I also want to be able to support other languages or fonts that might not contain the full character set that we use for an example.

**Comment by jrtashjian** [comment]
This functionality already exists :)

Paragraph, sentence, alphabet, and numerals have defaults but can be overridden in the block editor. Custom is the only one that can't which is meant for the site visitor to play around with the fonts.

**Comment by nickhamze** [comment]
oops sorry must have been using an old version or something.
