### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/quick-brown-fox#7]
What is this button on the QBF toolbar?

<img width="85" alt="screen shot 2019-01-18 at 10 42 40 am" src="https://user-images.githubusercontent.com/158918/51400361-d561ec00-1b0d-11e9-87d3-f38333b4da4b.png">

**Comment by jrtashjian** [comment]
Hmm, that shouldn't be showing because I've disabled functions in the toolbar since we didn't need them here. Maybe it was an update to the editor recently? Are you running just the core block editor or do you have the Gutenberg plugin active with unreleased features?

**Comment by nickhamze** [comment]
Nothing special just plain old 5.0.3.

It only shows up when I click on the text input area like I'm going to type something.
<img width="845" alt="screen shot 2019-01-18 at 11 47 23 am" src="https://user-images.githubusercontent.com/158918/51403697-d77c7880-1b16-11e9-9d3f-d72a8837076e.png">

vs this:

<img width="817" alt="screen shot 2019-01-18 at 11 46 41 am" src="https://user-images.githubusercontent.com/158918/51403703-db0fff80-1b16-11e9-821b-c3d5f8e6c7cd.png">

**Comment by jrtashjian** [comment]
Apparently this is from the CoBlocks plugin :)

Found a way to disable them (not just the core styles). Fixed in: 00a5e1285760c3108c8795493fac890de43132fd

**Comment by jrtashjian** [comment]
I actually had to revert this change as it was throwing an error and crashing the editor. This might not be something we can fix and might be a bug with the core editor.

**Comment by nickhamze** [comment]
Not a big deal. If it is a bug with the core editor maybe you can find a fix for it. Get your name in 5.1 . Shouldn't hurt business :) .
